order_acceptance_service/urls.py
from django.contrib import admin
from django.urls import path, include
from order_acceptance_service_abi.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('order_acceptance_service_abi.urls')),
    # namespace="users" - позволяет формировать пространство имен для доступа к URL-маршрутам (users:login)
    path('users/', include('users.urls', namespace="users")),
]

handler404 = page_not_found

users/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views


# создаем переменную, именнующую пространство имен
app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path(
        'password-reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done'),
                                  ),
        name='password_reset',
    ),
    path(
        'password-reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done',
    ),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url=reverse_lazy('users:password_reset_complete')
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label="Логин",
                    widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label="Пароль",
                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']

users/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .forms import LoginUserForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}

    def get_success_url(self):
        return reverse_lazy('start_page')


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div  class="container main">
    <h1>Авторизация</h1>

    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor %}
        <p><button type="submit">Войти</button></p>
        <p><a href="{% url 'users:password_reset' %}">Забыли пароль?</a></p>
    </form>
    <div class="main"></div>
</div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<div  class="container main">
  <h1>Пароль изменен.</h1>
  <p>
    Вы успешно изменили пароль своего аккаунта.
    <a href="{% url 'users:login' %}">Вход в систему.</a>
  </p>
<div class="main"></div>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<div  class="container main">
  <h1>Новый пароль</h1>
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    <div>
      {{ form.non_field_errors }}
    </div>
    {% for f in form %}
      <p>
        <label for="{{ f.id_for_label }}">{{ f.label }}</label>
        {{ f }}
      </p>
      <div>{{ f.errors }}</div>
    {% endfor %}
    <p>
      <button type="submit">Сохранить</button>
    </p>
  </form>
<div class="main"></div>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div  class="container main">
<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
<div class="main"></div>
</div>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<div  class="container main">
  <h1>Востановление пароля</h1>
  <form method="post">
    {% csrf_token %}
    {% for f in form %}
      <p>
        <label for="{{ f.id_for_label }}">{{ f.label }}</label>
        {{ f }}
      </p>
      <div>{{ f.errors }}</div>
    {% endfor %}
    <p>
      <button type="submit">Сбросить на E-mail</button>
    </p>
  </form>
  <div class="main"></div>
</div>
{% endblock %}