order_acceptance_service/urls.py
from django.contrib import admin
from django.urls import path, include
from order_acceptance_service_abi.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('order_acceptance_service_abi.urls')),
    # namespace="users" - позволяет формировать пространство имен для доступа к URL-маршрутам (users:login)
    path('users/', include('users.urls', namespace="users")),
]

handler404 = page_not_found

users/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views


# создаем переменную, именнующую пространство имен
app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path(
        'password-reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy('users:password_reset_done'),
                                  ),
        name='password_reset',
    ),
    path(
        'password-reset/done/',
        PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
        name='password_reset_done',
    ),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html',
             success_url=reverse_lazy('users:password_reset_complete')
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta
            name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
        />
    <title>{{ title }}</title>
    <link type="text/css" href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body style="
background: black;
background-image: url('{% static 'images/bg_img.jpg' %}');
background-size: cover;
background-repeat: no-repeat;
background-position: center center;
min-height: 100%;
background-attachment: fixed;
">
    <header class="container header">
        <div class="header_log">
            <div>LOGO</div>
            <div>Logo name</div>
            <div>
                <p>Контакты</p>
                <p>Менеджер</p>
                <p>телефон</p>
            </div>
        </div>
        <div class="header_nav">
            <div class="nav">
                {% if path == '/' %}
                    Главная страница
                {% else %}
                    <a href="{% url 'start_page' %}">Главная страница</a>
                {% endif %}
            </div>
            <div class="nav">
                {% if path == '/order/' %}
                    ЗАКАЗ
                {% else %}
                    <a href="{% url 'order' %}">ЗАКАЗ</a>
                {% endif %}
            </div>
            {% if user.is_superuser %}
                <div class="nav">
                    {% if path == '/upload/' %}
                        Обновить продукцию
                    {% else %}
                        <a href="{% url 'upload_file' %}">Обновить продукцию</a>
                    {% endif %}
                </div>
            {% endif %}
            <div class="main"></div>
            <div>
                <ul class="registration">
                    {% if user.is_authenticated %}
                    <li class="last"> {{user.username}} | <a href="{% url 'users:logout' %}">Выйти</a></li>
                    {% else %}
                    <li class="last"><a href="{% url 'users:login' %}">Войти</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </header>
    {% block content %}
    {% endblock %}
    <footer class="container footer">
        <div>LOGO</div>
        <div>
            <div>Техническая поддержка</div>
            <div>mail@mail.ru</div>
        </div>
    </footer>

</body>
</html>